// <auto-generated>
// This .cs file is generated by T4 template. Don't change it. Change the .tt file instead.
// </auto-generated>
#nullable enable

using System;
using System.Globalization;
using FastEnumUtility.UnitTests.Models;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace FastEnumUtility.UnitTests.Cases.Generators;



[TestClass]
public sealed class SameValueContinuousTests
{
    [TestMethod]
    public void GetName()
    {
        foreach (var x in Enum.GetValues<SameValueContinuousEnum>())
        {
            var expect = Enum.GetName(x);
            var actual = FastEnum.GetName<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x);
            actual.Should().Be(expect);
        }
    }


    [TestMethod]
    public void IsDefined()
    {
        //--- IsDefined(TEnum)
        FastEnum.IsDefined<SameValueContinuousEnum, SameValueContinuousEnumBooster>(SameValueContinuousEnum.A).Should().BeTrue();
        FastEnum.IsDefined<SameValueContinuousEnum, SameValueContinuousEnumBooster>(SameValueContinuousEnum.B).Should().BeTrue();
        FastEnum.IsDefined<SameValueContinuousEnum, SameValueContinuousEnumBooster>(SameValueContinuousEnum.C).Should().BeTrue();
        FastEnum.IsDefined<SameValueContinuousEnum, SameValueContinuousEnumBooster>(SameValueContinuousEnum.D).Should().BeTrue();
        FastEnum.IsDefined<SameValueContinuousEnum, SameValueContinuousEnumBooster>((SameValueContinuousEnum)123).Should().BeFalse();

        //--- IsDefined(ReadOnlySpan<char>)
        FastEnum.IsDefined<SameValueContinuousEnum, SameValueContinuousEnumBooster>(nameof(SameValueContinuousEnum.A)).Should().BeTrue();
        FastEnum.IsDefined<SameValueContinuousEnum, SameValueContinuousEnumBooster>(nameof(SameValueContinuousEnum.B)).Should().BeTrue();
        FastEnum.IsDefined<SameValueContinuousEnum, SameValueContinuousEnumBooster>(nameof(SameValueContinuousEnum.C)).Should().BeTrue();
        FastEnum.IsDefined<SameValueContinuousEnum, SameValueContinuousEnumBooster>(nameof(SameValueContinuousEnum.D)).Should().BeTrue();
        FastEnum.IsDefined<SameValueContinuousEnum, SameValueContinuousEnumBooster>("123").Should().BeFalse();
        FastEnum.IsDefined<SameValueContinuousEnum, SameValueContinuousEnumBooster>("value").Should().BeFalse();
    }


    [TestMethod]
    public void Parse()
    {
        var parameters = new[]
        {
            (value: SameValueContinuousEnum.A, name: nameof(SameValueContinuousEnum.A), valueString: ((byte)SameValueContinuousEnum.A).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueContinuousEnum.B, name: nameof(SameValueContinuousEnum.B), valueString: ((byte)SameValueContinuousEnum.B).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueContinuousEnum.C, name: nameof(SameValueContinuousEnum.C), valueString: ((byte)SameValueContinuousEnum.C).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueContinuousEnum.D, name: nameof(SameValueContinuousEnum.D), valueString: ((byte)SameValueContinuousEnum.D).ToString(CultureInfo.InvariantCulture)),
        };
        foreach (var x in parameters)
        {
            FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.name).Should().Be(x.value);
            FluentActions.Invoking(() => FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.name.ToLower(CultureInfo.InvariantCulture))).Should().Throw<ArgumentException>();
            FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.name.ToUpper(CultureInfo.InvariantCulture)).Should().Be(x.value);
            FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.valueString).Should().Be(x.value);
            FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.valueString.ToLower(CultureInfo.InvariantCulture)).Should().Be(x.value);
            FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.valueString.ToUpper(CultureInfo.InvariantCulture)).Should().Be(x.value);
        }
        FluentActions.Invoking(static () => FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>((string?)null)).Should().Throw<ArgumentException>();
        FluentActions.Invoking(static () => FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>("")).Should().Throw<ArgumentException>();
        FluentActions.Invoking(static () => FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(" ")).Should().Throw<ArgumentException>();
        FluentActions.Invoking(static () => FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>("ABCDE")).Should().Throw<ArgumentException>();
        FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>("123").Should().Be((SameValueContinuousEnum)123);
    }


    [TestMethod]
    public void ParseIgnoreCase()
    {
        var parameters = new[]
        {
            (value: SameValueContinuousEnum.A, name: nameof(SameValueContinuousEnum.A), valueString: ((byte)SameValueContinuousEnum.A).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueContinuousEnum.B, name: nameof(SameValueContinuousEnum.B), valueString: ((byte)SameValueContinuousEnum.B).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueContinuousEnum.C, name: nameof(SameValueContinuousEnum.C), valueString: ((byte)SameValueContinuousEnum.C).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueContinuousEnum.D, name: nameof(SameValueContinuousEnum.D), valueString: ((byte)SameValueContinuousEnum.D).ToString(CultureInfo.InvariantCulture)),
        };
        foreach (var x in parameters)
        {
            FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.name, true).Should().Be(x.value);
            FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.name.ToLower(CultureInfo.InvariantCulture), true).Should().Be(x.value);
            FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.name.ToUpper(CultureInfo.InvariantCulture), true).Should().Be(x.value);
            FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.valueString, true).Should().Be(x.value);
            FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.valueString.ToLower(CultureInfo.InvariantCulture), true).Should().Be(x.value);
            FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.valueString.ToUpper(CultureInfo.InvariantCulture), true).Should().Be(x.value);
        }
        FluentActions.Invoking(static () => FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>((string?)null, true)).Should().Throw<ArgumentException>();
        FluentActions.Invoking(static () => FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>("", true)).Should().Throw<ArgumentException>();
        FluentActions.Invoking(static () => FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(" ", true)).Should().Throw<ArgumentException>();
        FluentActions.Invoking(static () => FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>("ABCDE", true)).Should().Throw<ArgumentException>();
        FastEnum.Parse<SameValueContinuousEnum, SameValueContinuousEnumBooster>("123", true).Should().Be((SameValueContinuousEnum)123);
    }


    [TestMethod]
    public void TryParse()
    {
        var parameters = new[]
        {
            (value: SameValueContinuousEnum.A, name: nameof(SameValueContinuousEnum.A), valueString: ((byte)SameValueContinuousEnum.A).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueContinuousEnum.B, name: nameof(SameValueContinuousEnum.B), valueString: ((byte)SameValueContinuousEnum.B).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueContinuousEnum.C, name: nameof(SameValueContinuousEnum.C), valueString: ((byte)SameValueContinuousEnum.C).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueContinuousEnum.D, name: nameof(SameValueContinuousEnum.D), valueString: ((byte)SameValueContinuousEnum.D).ToString(CultureInfo.InvariantCulture)),
        };
        foreach (var x in parameters)
        {
            FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.name, out var r1).Should().BeTrue();
            r1.Should().Be(x.value);

            FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.name.ToLower(CultureInfo.InvariantCulture), out var _).Should().BeFalse();
            FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.name.ToUpper(CultureInfo.InvariantCulture), out var _).Should().BeTrue();

            FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.valueString, out var r2).Should().BeTrue();
            r2.Should().Be(x.value);

            FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.valueString.ToLower(CultureInfo.InvariantCulture), out var r3).Should().BeTrue();
            r3.Should().Be(x.value);

            FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.valueString.ToUpper(CultureInfo.InvariantCulture), out var r4).Should().BeTrue();
            r4.Should().Be(x.value);
        }
        FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>((string?)null, out var _).Should().BeFalse();
        FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>("", out var _).Should().BeFalse();
        FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(" ", out var _).Should().BeFalse();
        FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>("ABCDE", out var _).Should().BeFalse();
        FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>("123", out var r).Should().BeTrue();
        r.Should().Be((SameValueContinuousEnum)123);
    }


    [TestMethod]
    public void TryParseIgnoreCase()
    {
        var parameters = new[]
        {
            (value: SameValueContinuousEnum.A, name: nameof(SameValueContinuousEnum.A), valueString: ((byte)SameValueContinuousEnum.A).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueContinuousEnum.B, name: nameof(SameValueContinuousEnum.B), valueString: ((byte)SameValueContinuousEnum.B).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueContinuousEnum.C, name: nameof(SameValueContinuousEnum.C), valueString: ((byte)SameValueContinuousEnum.C).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueContinuousEnum.D, name: nameof(SameValueContinuousEnum.D), valueString: ((byte)SameValueContinuousEnum.D).ToString(CultureInfo.InvariantCulture)),
        };
        foreach (var x in parameters)
        {
            FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.name, true, out var r1).Should().BeTrue();
            r1.Should().Be(x.value);

            FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.name.ToLower(CultureInfo.InvariantCulture), true, out var r2).Should().BeTrue();
            r2.Should().Be(x.value);

            FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.name.ToUpper(CultureInfo.InvariantCulture), true, out var r3).Should().BeTrue();
            r3.Should().Be(x.value);

            FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.valueString, true, out var r4).Should().BeTrue();
            r4.Should().Be(x.value);

            FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.valueString.ToLower(CultureInfo.InvariantCulture), true, out var r5).Should().BeTrue();
            r5.Should().Be(x.value);

            FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x.valueString.ToUpper(CultureInfo.InvariantCulture), true, out var r6).Should().BeTrue();
            r6.Should().Be(x.value);
        }
        FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>((string?)null, true, out var _).Should().BeFalse();
        FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>("", true, out var _).Should().BeFalse();
        FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>(" ", true, out var _).Should().BeFalse();
        FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>("ABCDE", true, out var _).Should().BeFalse();
        FastEnum.TryParse<SameValueContinuousEnum, SameValueContinuousEnumBooster>("123", true, out var r).Should().BeTrue();
        r.Should().Be((SameValueContinuousEnum)123);
    }


    [TestMethod]
    public void FastToString()
    {
        var values = Enum.GetValues<SameValueContinuousEnum>();
        foreach (var x in values)
        {
            var expect = Enum.GetName(x);
            var actual = FastEnum.ToString<SameValueContinuousEnum, SameValueContinuousEnumBooster>(x);
            actual.Should().Be(expect);
        }
    }
}



[TestClass]
public sealed class SameValueDiscontinuousTests
{
    [TestMethod]
    public void GetName()
    {
        foreach (var x in Enum.GetValues<SameValueDiscontinuousEnum>())
        {
            var expect = Enum.GetName(x);
            var actual = FastEnum.GetName<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x);
            actual.Should().Be(expect);
        }
    }


    [TestMethod]
    public void IsDefined()
    {
        //--- IsDefined(TEnum)
        FastEnum.IsDefined<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(SameValueDiscontinuousEnum.A).Should().BeTrue();
        FastEnum.IsDefined<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(SameValueDiscontinuousEnum.B).Should().BeTrue();
        FastEnum.IsDefined<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(SameValueDiscontinuousEnum.C).Should().BeTrue();
        FastEnum.IsDefined<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(SameValueDiscontinuousEnum.D).Should().BeTrue();
        FastEnum.IsDefined<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>((SameValueDiscontinuousEnum)123).Should().BeFalse();

        //--- IsDefined(ReadOnlySpan<char>)
        FastEnum.IsDefined<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(nameof(SameValueDiscontinuousEnum.A)).Should().BeTrue();
        FastEnum.IsDefined<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(nameof(SameValueDiscontinuousEnum.B)).Should().BeTrue();
        FastEnum.IsDefined<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(nameof(SameValueDiscontinuousEnum.C)).Should().BeTrue();
        FastEnum.IsDefined<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(nameof(SameValueDiscontinuousEnum.D)).Should().BeTrue();
        FastEnum.IsDefined<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>("123").Should().BeFalse();
        FastEnum.IsDefined<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>("value").Should().BeFalse();
    }


    [TestMethod]
    public void Parse()
    {
        var parameters = new[]
        {
            (value: SameValueDiscontinuousEnum.A, name: nameof(SameValueDiscontinuousEnum.A), valueString: ((byte)SameValueDiscontinuousEnum.A).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueDiscontinuousEnum.B, name: nameof(SameValueDiscontinuousEnum.B), valueString: ((byte)SameValueDiscontinuousEnum.B).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueDiscontinuousEnum.C, name: nameof(SameValueDiscontinuousEnum.C), valueString: ((byte)SameValueDiscontinuousEnum.C).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueDiscontinuousEnum.D, name: nameof(SameValueDiscontinuousEnum.D), valueString: ((byte)SameValueDiscontinuousEnum.D).ToString(CultureInfo.InvariantCulture)),
        };
        foreach (var x in parameters)
        {
            FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.name).Should().Be(x.value);
            FluentActions.Invoking(() => FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.name.ToLower(CultureInfo.InvariantCulture))).Should().Throw<ArgumentException>();
            FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.name.ToUpper(CultureInfo.InvariantCulture)).Should().Be(x.value);
            FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.valueString).Should().Be(x.value);
            FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.valueString.ToLower(CultureInfo.InvariantCulture)).Should().Be(x.value);
            FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.valueString.ToUpper(CultureInfo.InvariantCulture)).Should().Be(x.value);
        }
        FluentActions.Invoking(static () => FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>((string?)null)).Should().Throw<ArgumentException>();
        FluentActions.Invoking(static () => FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>("")).Should().Throw<ArgumentException>();
        FluentActions.Invoking(static () => FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(" ")).Should().Throw<ArgumentException>();
        FluentActions.Invoking(static () => FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>("ABCDE")).Should().Throw<ArgumentException>();
        FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>("123").Should().Be((SameValueDiscontinuousEnum)123);
    }


    [TestMethod]
    public void ParseIgnoreCase()
    {
        var parameters = new[]
        {
            (value: SameValueDiscontinuousEnum.A, name: nameof(SameValueDiscontinuousEnum.A), valueString: ((byte)SameValueDiscontinuousEnum.A).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueDiscontinuousEnum.B, name: nameof(SameValueDiscontinuousEnum.B), valueString: ((byte)SameValueDiscontinuousEnum.B).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueDiscontinuousEnum.C, name: nameof(SameValueDiscontinuousEnum.C), valueString: ((byte)SameValueDiscontinuousEnum.C).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueDiscontinuousEnum.D, name: nameof(SameValueDiscontinuousEnum.D), valueString: ((byte)SameValueDiscontinuousEnum.D).ToString(CultureInfo.InvariantCulture)),
        };
        foreach (var x in parameters)
        {
            FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.name, true).Should().Be(x.value);
            FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.name.ToLower(CultureInfo.InvariantCulture), true).Should().Be(x.value);
            FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.name.ToUpper(CultureInfo.InvariantCulture), true).Should().Be(x.value);
            FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.valueString, true).Should().Be(x.value);
            FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.valueString.ToLower(CultureInfo.InvariantCulture), true).Should().Be(x.value);
            FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.valueString.ToUpper(CultureInfo.InvariantCulture), true).Should().Be(x.value);
        }
        FluentActions.Invoking(static () => FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>((string?)null, true)).Should().Throw<ArgumentException>();
        FluentActions.Invoking(static () => FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>("", true)).Should().Throw<ArgumentException>();
        FluentActions.Invoking(static () => FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(" ", true)).Should().Throw<ArgumentException>();
        FluentActions.Invoking(static () => FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>("ABCDE", true)).Should().Throw<ArgumentException>();
        FastEnum.Parse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>("123", true).Should().Be((SameValueDiscontinuousEnum)123);
    }


    [TestMethod]
    public void TryParse()
    {
        var parameters = new[]
        {
            (value: SameValueDiscontinuousEnum.A, name: nameof(SameValueDiscontinuousEnum.A), valueString: ((byte)SameValueDiscontinuousEnum.A).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueDiscontinuousEnum.B, name: nameof(SameValueDiscontinuousEnum.B), valueString: ((byte)SameValueDiscontinuousEnum.B).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueDiscontinuousEnum.C, name: nameof(SameValueDiscontinuousEnum.C), valueString: ((byte)SameValueDiscontinuousEnum.C).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueDiscontinuousEnum.D, name: nameof(SameValueDiscontinuousEnum.D), valueString: ((byte)SameValueDiscontinuousEnum.D).ToString(CultureInfo.InvariantCulture)),
        };
        foreach (var x in parameters)
        {
            FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.name, out var r1).Should().BeTrue();
            r1.Should().Be(x.value);

            FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.name.ToLower(CultureInfo.InvariantCulture), out var _).Should().BeFalse();
            FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.name.ToUpper(CultureInfo.InvariantCulture), out var _).Should().BeTrue();

            FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.valueString, out var r2).Should().BeTrue();
            r2.Should().Be(x.value);

            FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.valueString.ToLower(CultureInfo.InvariantCulture), out var r3).Should().BeTrue();
            r3.Should().Be(x.value);

            FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.valueString.ToUpper(CultureInfo.InvariantCulture), out var r4).Should().BeTrue();
            r4.Should().Be(x.value);
        }
        FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>((string?)null, out var _).Should().BeFalse();
        FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>("", out var _).Should().BeFalse();
        FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(" ", out var _).Should().BeFalse();
        FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>("ABCDE", out var _).Should().BeFalse();
        FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>("123", out var r).Should().BeTrue();
        r.Should().Be((SameValueDiscontinuousEnum)123);
    }


    [TestMethod]
    public void TryParseIgnoreCase()
    {
        var parameters = new[]
        {
            (value: SameValueDiscontinuousEnum.A, name: nameof(SameValueDiscontinuousEnum.A), valueString: ((byte)SameValueDiscontinuousEnum.A).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueDiscontinuousEnum.B, name: nameof(SameValueDiscontinuousEnum.B), valueString: ((byte)SameValueDiscontinuousEnum.B).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueDiscontinuousEnum.C, name: nameof(SameValueDiscontinuousEnum.C), valueString: ((byte)SameValueDiscontinuousEnum.C).ToString(CultureInfo.InvariantCulture)),
            (value: SameValueDiscontinuousEnum.D, name: nameof(SameValueDiscontinuousEnum.D), valueString: ((byte)SameValueDiscontinuousEnum.D).ToString(CultureInfo.InvariantCulture)),
        };
        foreach (var x in parameters)
        {
            FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.name, true, out var r1).Should().BeTrue();
            r1.Should().Be(x.value);

            FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.name.ToLower(CultureInfo.InvariantCulture), true, out var r2).Should().BeTrue();
            r2.Should().Be(x.value);

            FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.name.ToUpper(CultureInfo.InvariantCulture), true, out var r3).Should().BeTrue();
            r3.Should().Be(x.value);

            FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.valueString, true, out var r4).Should().BeTrue();
            r4.Should().Be(x.value);

            FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.valueString.ToLower(CultureInfo.InvariantCulture), true, out var r5).Should().BeTrue();
            r5.Should().Be(x.value);

            FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x.valueString.ToUpper(CultureInfo.InvariantCulture), true, out var r6).Should().BeTrue();
            r6.Should().Be(x.value);
        }
        FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>((string?)null, true, out var _).Should().BeFalse();
        FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>("", true, out var _).Should().BeFalse();
        FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(" ", true, out var _).Should().BeFalse();
        FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>("ABCDE", true, out var _).Should().BeFalse();
        FastEnum.TryParse<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>("123", true, out var r).Should().BeTrue();
        r.Should().Be((SameValueDiscontinuousEnum)123);
    }


    [TestMethod]
    public void FastToString()
    {
        var values = Enum.GetValues<SameValueDiscontinuousEnum>();
        foreach (var x in values)
        {
            var expect = Enum.GetName(x);
            var actual = FastEnum.ToString<SameValueDiscontinuousEnum, SameValueDiscontinuousEnumBooster>(x);
            actual.Should().Be(expect);
        }
    }
}



